#!/usr/bin/env bash
# make apache server that returns Hello Holberton 

sudo apt-get update
sudo apt-get install -y apache2

echo "Hello Holberton" | sudo tee /var/www/html/index.html

sudo service apache2 start
