#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing Holberton School

sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start

