#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing Holberton School

sudo apt-get update
sudo apt-get install -y nginx
ufw enable
ufw allow 'Nginx HTTP'
ufw allow 'OpenSSH'
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start

