#!/usr/bin/env bash
# installs nginx and configures a 301 redirect from /redirect_me

sudo apt-get update -y
sudo apt-get install -y nginx

 sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
