#!/usr/bin/env bash
# Installs Nginx and configures a custom 404 error page

sudo apt-get update -y
sudo apt-get install -y nginx

# Create the custom 404 page with the required content
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Tell Nginx to use this file when a 404 error happens
sudo sed -i '/server_name _;/a \\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
